# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/m8/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/m8/proprietary/vendor/blobs/gsm/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/bin/netmgrd \
    vendor/htc/m8/proprietary/vendor/blobs/gsm/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/bin/qmuxd \
    vendor/htc/m8/proprietary/vendor/blobs/gsm/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libmdmdetect.so \
    vendor/htc/m8/proprietary/vendor/blobs/gsm/lib/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libcneapiclient.so \
    vendor/htc/m8/proprietary/vendor/blobs/gsm/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libconfigdb.so \
    vendor/htc/m8/proprietary/vendor/blobs/gsm/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libnetmgr.so \
    vendor/htc/m8/proprietary/vendor/blobs/gsm/lib/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libperipheral_client.so \
    vendor/htc/m8/proprietary/vendor/blobs/gsm/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libril-qc-qmi-1.so \
    vendor/htc/m8/proprietary/vendor/blobs/gsm/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/blobs/gsm/lib/libril-qcril-hook-oem.so \
    vendor/htc/m8/proprietary/vendor/blobs/spr/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/bin/netmgrd \
    vendor/htc/m8/proprietary/vendor/blobs/spr/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/bin/qmuxd \
    vendor/htc/m8/proprietary/vendor/blobs/spr/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libmdmdetect.so \
    vendor/htc/m8/proprietary/vendor/blobs/spr/lib/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libcneapiclient.so \
    vendor/htc/m8/proprietary/vendor/blobs/spr/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libconfigdb.so \
    vendor/htc/m8/proprietary/vendor/blobs/spr/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libnetmgr.so \
    vendor/htc/m8/proprietary/vendor/blobs/spr/lib/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libperipheral_client.so \
    vendor/htc/m8/proprietary/vendor/blobs/spr/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libril-qc-qmi-1.so \
    vendor/htc/m8/proprietary/vendor/blobs/spr/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/blobs/spr/lib/libril-qcril-hook-oem.so \
    vendor/htc/m8/proprietary/vendor/blobs/vzw/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/bin/netmgrd \
    vendor/htc/m8/proprietary/vendor/blobs/vzw/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/bin/qmuxd \
    vendor/htc/m8/proprietary/vendor/blobs/vzw/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libmdmdetect.so \
    vendor/htc/m8/proprietary/vendor/blobs/vzw/lib/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libcneapiclient.so \
    vendor/htc/m8/proprietary/vendor/blobs/vzw/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libconfigdb.so \
    vendor/htc/m8/proprietary/vendor/blobs/vzw/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libnetmgr.so \
    vendor/htc/m8/proprietary/vendor/blobs/vzw/lib/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libperipheral_client.so \
    vendor/htc/m8/proprietary/vendor/blobs/vzw/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libril-qc-qmi-1.so \
    vendor/htc/m8/proprietary/vendor/blobs/vzw/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/blobs/vzw/lib/libril-qcril-hook-oem.so
